# Generated by Django 5.1.1 on 2024-09-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autocarros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(auto_now_add=True)),
                ('codigo_bilhete', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=12)),
                ('senha', models.CharField(max_length=100)),
                ('data_criacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.provincias')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pagamento', models.CharField(max_length=100)),
                ('status_pagamento', models.CharField(max_length=100)),
                ('data_pagamento', models.DateField()),
                ('bilhete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.bilhete')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='bilhete',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
        migrations.CreateModel(
            name='Viagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_partida', models.DateField()),
                ('hora', models.CharField(max_length=6)),
                ('preco', models.FloatField()),
                ('lugar_disponivel', models.IntegerField()),
                ('autocarro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.autocarros')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens_destino', to='usuarios.estacoes')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens_origem', to='usuarios.estacoes')),
            ],
        ),
        migrations.AddField(
            model_name='bilhete',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.viagens'),
        ),
    ]
